soft-fail: false
skip-check:
  # API Gateway caching - not needed for a simple health check endpoint
  - CKV_AWS_120
  - CKV_AWS_225
  # Deploy role requires broad write access for Terraform operations
  - CKV_AWS_290
  # EC2/VPC operations require wildcard resource (AWS limitation)
  - CKV_AWS_355
  # Client certificate auth - using API key auth instead
  - CKV2_AWS_51
  # Default VPC security group - managed separately from Lambda SG
  - CKV2_AWS_12
  # Security group attachment - Lambda SG is attached via Lambda VPC config
  - CKV2_AWS_5
  # KMS key policy - using default key policy which grants account-level access
  - CKV2_AWS_64
  # VPC flow logging - out of scope for health check demo project
  - CKV2_AWS_11
  # Lambda concurrent execution limit - not needed for demo workload
  - CKV_AWS_115
  # Lambda DLQ - health check is synchronous, DLQ not applicable
  - CKV_AWS_116
  # Lambda code-signing - not applicable for this deployment model
  - CKV_AWS_272
  # API Gateway request validation - validation handled in Lambda code
  - CKV2_AWS_53
